services:
  - type: worker
    name: trading-bot-macd
    runtime: python
    repo: https://github.com/LEONARDOSUSA/trading-bot-estrategia-macd
    buildCommand: |
      pip install -r requirements.txt
      pip install .
    startCommand: python trading_loop.py
    region: oregon
    plan: free
    envVars:
      - key: ALPACA_KEY
        sync: false
      - key: ALPACA_SECRET
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
